# Generated by Django 5.2.5 on 2026-03-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_spotlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='spotlight_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
