# Generated by Django 5.2.5 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_resource_resourcesubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceSubmission',
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
