# Generated by Django 5.2.5 on 2026-03-17 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_business_is_spotlight_business_spotlight_added_at'),
        ('app', '0007_delete_resource_delete_resourcesubmission_and_more'),
    ]

    operations = [
    ]
